### ISSUE TITLE
The Chip8  Bug

### ISSUE THREAD

**Issue by beckysophie** [dkanada/Chip8#2]
***Expected Behavior***

The app should allow users access their settings properly and adjust to their choice

***Actual Behavior***

It crashes at every click on settings 

***Test Tools**
* Operating system : Android 6.0
* Phone : Infinix hot s
* Chip8 version 0.7

***How to produce the bug***

Open the app, select more options and click on settings. It will crash 

*Recording of the bug is shown below......*

https://youtu.be/tG4LfcRwqvA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/the-chip8-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dkanada** [comment]
It was a silly mistake, I just pushed a new update that should fix the settings.
