### ISSUE TITLE
Buttons on App do not respond {BUG}

### ISSUE THREAD

**Issue by beckysophie** [dkanada/Chip8#4]
***Expected Behavior***

Buttons on the app should respond and clickable 

***Actual Behavior***

Buttons do not respond.... Buttons appear useless 

***Test Tools**

* Operating system : Android 6.0
* Phone : Infinix hot s
* Chip8 version 0.7.1

***How to produce the bug***

Open the app, click on the buttons shown and the App.... They won't respond 

*Recording of the bug is shown below......*

https://youtu.be/idTVcPRkHHo

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/buttons-on-app-do-not-respond-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dkanada** [comment]
The buttons will not do anything if no game is loaded. I might add a ripple animation in the future.
