### ISSUE TITLE
Can't Change the Foreground Color in Chip8. 

### ISSUE THREAD

**Issue by wanizubair** [dkanada/Chip8#8]
#### Expected behavior

+ The App should be able to change the color for the display foreground. 

#### Actual behavior
The app is not able to change the color for the display foreground.

#### How to reproduce

+ Launch the application. 

+ Click on the icon right at the top corner of the app you see two options there.

+ Click on Settings option. 

+ Click on Foreground Color. 

+ Pick any color, it doesn't work and you are not able to change the Foreground color. 
* Application :Chip8
* Operating system:Android 7.0

#### Recording Of The Bug

https://youtu.be/tFzz-czWaxs    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/can-t-change-the-foreground-color-in-chip8">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dkanada** [comment]
The foreground color is only visible when a game is loaded. This is different from the primary color, which is not customizable at the moment.
